// SPDX-License-Identifier: Apache-2.0
/*
 * Copyright (c) 2026 Sunnyside Labs Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Originally generated by gnark (https://github.com/consensys/gnark)
 * Modified by Sunnyside Labs Inc.
 */
pragma solidity 0.8.34;

import {Ownable2Step, Ownable} from "@openzeppelin/contracts/access/Ownable2Step.sol";

/// @title Groth16Verifier
/// @notice Abstract base contract for Groth16 proof verification with SSTORE2-based VK storage
/// @dev Supports multiple circuit configurations via parameterized VK registry
abstract contract Groth16Verifier is Ownable2Step {
    error VerifyingKeyNotFound();
    error InvalidPublicInputLength();
    error PublicInputNotInField();
    error PrecompileCallFailed();
    error ProofInvalid();
    error InvalidParam();
    error EmptyICSources();
    error ICSourceMismatch();
    error InvalidVKConstants();
    error InvalidICLength();

    /// @dev BN254 scalar field modulus
    uint256 internal constant R = 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001;

    /// @dev VK constants size: 14 * 32 = 448 bytes (alpha, betaNeg, gammaNeg, deltaNeg)
    uint256 internal constant VK_CONSTANTS_SIZE = 448;

    /// @dev Pointers to SSTORE2 data contracts containing verifying key components
    struct VKPointers {
        address[] icxSources; // SSTORE2 contracts for IC X coordinates
        address[] icySources; // SSTORE2 contracts for IC Y coordinates
        address vkConstants; // SSTORE2 contract for alpha, beta, gamma, delta
        uint256 icLen; // IC array length (publicInputs.length + 1)
    }

    mapping(uint32 circuitParam => VKPointers vkPointers) internal vkRegistry;

    /// @dev Supported parameters for enumeration
    uint32[] public supportedParams;

    /// @notice True if a circuit parameter is supported
    mapping(uint32 circuitParam => bool supported) public isSupported;

    constructor(address initialOwner) Ownable(initialOwner) {}

    /// @notice Register a verifying key for a specific circuit parameter
    /// @param param Circuit parameter (batchSize or maxInputs)
    /// @param icxSources_ SSTORE2 contracts containing IC X coordinates
    /// @param icySources_ SSTORE2 contracts containing IC Y coordinates
    /// @param vkConstants_ SSTORE2 contract containing alpha, beta, gamma, delta
    /// @param icLen_ Length of IC array (publicInputs.length + 1)
    function registerVK(
        uint32 param,
        address[] calldata icxSources_,
        address[] calldata icySources_,
        address vkConstants_,
        uint256 icLen_
    ) external onlyOwner {
        if (param == 0) revert InvalidParam();
        if (icxSources_.length == 0) revert EmptyICSources();
        if (icxSources_.length != icySources_.length) revert ICSourceMismatch();
        if (vkConstants_ == address(0)) revert InvalidVKConstants();
        if (icLen_ == 0) revert InvalidICLength();

        VKPointers storage vk = vkRegistry[param];
        vk.icxSources = icxSources_;
        vk.icySources = icySources_;
        vk.vkConstants = vkConstants_;
        vk.icLen = icLen_;

        if (!isSupported[param]) {
            supportedParams.push(param);
            isSupported[param] = true;
        }
    }

    /// @notice Get VK info for a specific parameter
    /// @param param Circuit parameter
    /// @return icLen IC array length
    /// @return vkConstants Address of VK constants contract
    function getVKInfo(uint32 param) external view returns (uint256 icLen, address vkConstants) {
        VKPointers storage vk = vkRegistry[param];
        icLen = vk.icLen;
        vkConstants = vk.vkConstants;
    }

    /// @dev Internal verification with SSTORE2 VK loading
    /// @param proofOffset Calldata offset where proof[8] starts
    /// @param publicInputs Public inputs to the circuit
    /// @param vk VK pointers for this circuit configuration
    function _verifyProof(uint256 proofOffset, uint256[] calldata publicInputs, VKPointers storage vk) internal view {
        uint256 icLen = vk.icLen;
        if (publicInputs.length + 1 != icLen) revert InvalidPublicInputLength();

        // Load VK pointers from storage to memory
        address[] memory icxSources = vk.icxSources;
        address[] memory icySources = vk.icySources;
        address vkConstAddr = vk.vkConstants;

        bool success;

        assembly ("memory-safe") {
            // Memory layout (relative to mem = mload(0x40)):
            // [0x00-0x40]: accumulator point for MSM (2 words)
            // [0x40-0xA0]: scratch space for ecMul input (3 words)
            // [0xA0-0x3A0]: pairing input (4 pairs * 6 words = 24 words = 0x300 bytes)
            // [0x3A0, 0x3A0+icBytes): icX data
            // [0x3A0+icBytes, 0x3A0+2*icBytes): icY data
            // [0x3A0+2*icBytes, ...): vkConstants data
            let mem := mload(0x40)
            let acc := mem
            let scratch := add(mem, 0x40)
            let pairingInput := add(mem, 0xA0)

            // Calculate IC bytes: icLen * 32
            let icBytes := shl(5, icLen)
            let icX := add(mem, 0x3A0)
            let icY := add(icX, icBytes)
            let vkConst := add(icY, icBytes)

            // Load IC X coordinates from SSTORE2 contracts
            {
                let srcLen := mload(icxSources)
                let srcPtr := add(icxSources, 0x20)
                let dest := icX
                for { let i := 0 } lt(i, srcLen) { i := add(i, 1) } {
                    let addr := mload(add(srcPtr, shl(5, i)))
                    if iszero(addr) { continue }
                    // SSTORE2: bytecode = 0x00 || data, so dataLen = codesize - 1
                    let dataLen := sub(extcodesize(addr), 1)
                    // Copy data from offset 1 (skip STOP opcode)
                    extcodecopy(addr, dest, 1, dataLen)
                    dest := add(dest, dataLen)
                }
            }

            // Load IC Y coordinates from SSTORE2 contracts
            {
                let srcLen := mload(icySources)
                let srcPtr := add(icySources, 0x20)
                let dest := icY
                for { let i := 0 } lt(i, srcLen) { i := add(i, 1) } {
                    let addr := mload(add(srcPtr, shl(5, i)))
                    if iszero(addr) { continue }
                    let dataLen := sub(extcodesize(addr), 1)
                    extcodecopy(addr, dest, 1, dataLen)
                    dest := add(dest, dataLen)
                }
            }

            // Load VK constants from SSTORE2 contract
            {
                let dataLen := sub(extcodesize(vkConstAddr), 1)
                extcodecopy(vkConstAddr, vkConst, 1, dataLen)
            }

            // Initialize accumulator with IC[0]
            mstore(acc, mload(icX))
            mstore(add(acc, 0x20), mload(icY))

            // MSM: acc += publicInputs[i] * IC[i+1]
            let inputLen := publicInputs.length
            let inputOffset := publicInputs.offset
            for { let i := 0 } lt(i, inputLen) { i := add(i, 1) } {
                let offset := shl(5, i)
                let icOffset := shl(5, add(i, 1))

                // Load IC[i+1] point
                mstore(scratch, mload(add(icX, icOffset)))
                mstore(add(scratch, 0x20), mload(add(icY, icOffset)))

                // Load scalar (public input)
                let s := calldataload(add(inputOffset, offset))
                mstore(add(scratch, 0x40), s)

                // Check scalar < R
                if iszero(lt(s, R)) {
                    mstore(0x00, 0xa54f8e27) // PublicInputNotInField()
                    revert(0x1c, 0x04)
                }

                // ecMul: scratch = s * IC[i+1]
                if iszero(staticcall(gas(), 0x07, scratch, 0x60, scratch, 0x40)) {
                    mstore(0x00, 0xfd23ff64) // PrecompileCallFailed()
                    revert(0x1c, 0x04)
                }

                // ecAdd: acc = acc + scratch
                mstore(add(acc, 0x40), mload(scratch))
                mstore(add(acc, 0x60), mload(add(scratch, 0x20)))
                if iszero(staticcall(gas(), 0x06, acc, 0x80, acc, 0x40)) {
                    mstore(0x00, 0xfd23ff64) // PrecompileCallFailed()
                    revert(0x1c, 0x04)
                }
            }

            // Build pairing input for ecPairing precompile
            // Pairing: e(A, B) * e(alpha, -beta) * e(acc, -gamma) * e(C, -delta) == 1

            // Pair 1: (proof.A, proof.B)
            mstore(pairingInput, calldataload(proofOffset)) // A.x
            mstore(add(pairingInput, 0x20), calldataload(add(proofOffset, 0x20))) // A.y
            mstore(add(pairingInput, 0x40), calldataload(add(proofOffset, 0x40))) // B.x[1]
            mstore(add(pairingInput, 0x60), calldataload(add(proofOffset, 0x60))) // B.x[0]
            mstore(add(pairingInput, 0x80), calldataload(add(proofOffset, 0x80))) // B.y[1]
            mstore(add(pairingInput, 0xa0), calldataload(add(proofOffset, 0xa0))) // B.y[0]

            // Pair 2: (alpha, betaNeg) - from VK constants
            // VK layout: alpha.x, alpha.y, betaNeg.x1, betaNeg.x0, betaNeg.y1, betaNeg.y0, ...
            mstore(add(pairingInput, 0xc0), mload(vkConst)) // alpha.x
            mstore(add(pairingInput, 0xe0), mload(add(vkConst, 0x20))) // alpha.y
            mstore(add(pairingInput, 0x100), mload(add(vkConst, 0x40))) // betaNeg.x1
            mstore(add(pairingInput, 0x120), mload(add(vkConst, 0x60))) // betaNeg.x0
            mstore(add(pairingInput, 0x140), mload(add(vkConst, 0x80))) // betaNeg.y1
            mstore(add(pairingInput, 0x160), mload(add(vkConst, 0xa0))) // betaNeg.y0

            // Pair 3: (acc, gammaNeg)
            mstore(add(pairingInput, 0x180), mload(acc)) // acc.x
            mstore(add(pairingInput, 0x1a0), mload(add(acc, 0x20))) // acc.y
            mstore(add(pairingInput, 0x1c0), mload(add(vkConst, 0xc0))) // gammaNeg.x1
            mstore(add(pairingInput, 0x1e0), mload(add(vkConst, 0xe0))) // gammaNeg.x0
            mstore(add(pairingInput, 0x200), mload(add(vkConst, 0x100))) // gammaNeg.y1
            mstore(add(pairingInput, 0x220), mload(add(vkConst, 0x120))) // gammaNeg.y0

            // Pair 4: (proof.C, deltaNeg)
            mstore(add(pairingInput, 0x240), calldataload(add(proofOffset, 0xc0))) // C.x
            mstore(add(pairingInput, 0x260), calldataload(add(proofOffset, 0xe0))) // C.y
            mstore(add(pairingInput, 0x280), mload(add(vkConst, 0x140))) // deltaNeg.x1
            mstore(add(pairingInput, 0x2a0), mload(add(vkConst, 0x160))) // deltaNeg.x0
            mstore(add(pairingInput, 0x2c0), mload(add(vkConst, 0x180))) // deltaNeg.y1
            mstore(add(pairingInput, 0x2e0), mload(add(vkConst, 0x1a0))) // deltaNeg.y0

            // Call ecPairing precompile (0x08)
            success := staticcall(gas(), 0x08, pairingInput, 0x300, pairingInput, 0x20)
            success := and(success, mload(pairingInput))
        }

        if (!success) revert ProofInvalid();
    }
}
