// SPDX-License-Identifier: Apache-2.0
/*
 * Copyright (c) 2026 Sunnyside Labs Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Originally generated by gnark (https://github.com/consensys/gnark)
 * Modified by Sunnyside Labs Inc.
 */
pragma solidity 0.8.34;

import {Groth16Verifier} from "./Groth16Verifier.sol";

/// @title Groth16EpochVerifier
/// @notice Groth16 verifier for epoch proofs with N-in M-out support
contract Groth16EpochVerifier is Groth16Verifier {
    mapping(
        uint32 maxTransfers
            => mapping(uint32 maxInputsPerTransfer => mapping(uint32 maxOutputsPerTransfer => VKPointers))
    ) internal epochVkRegistry;

    constructor(address initialOwner) Groth16Verifier(initialOwner) {}

    /// @notice Register a verifying key for a specific epoch circuit configuration
    /// @param maxTransfers Maximum number of transfers in circuit
    /// @param maxInputsPerTransfer Maximum inputs per transfer
    /// @param maxOutputsPerTransfer Maximum outputs per transfer
    /// @param icxSources_ SSTORE2 contracts containing IC X coordinates
    /// @param icySources_ SSTORE2 contracts containing IC Y coordinates
    /// @param vkConstants_ SSTORE2 contract containing alpha, beta, gamma, delta
    /// @param icLen_ Length of IC array (publicInputs.length + 1)
    function registerEpochVK(
        uint32 maxTransfers,
        uint32 maxInputsPerTransfer,
        uint32 maxOutputsPerTransfer,
        address[] calldata icxSources_,
        address[] calldata icySources_,
        address vkConstants_,
        uint256 icLen_
    ) external onlyOwner {
        if (maxTransfers == 0 || maxInputsPerTransfer == 0 || maxOutputsPerTransfer == 0) revert InvalidParam();
        if (icxSources_.length == 0) revert EmptyICSources();
        if (icxSources_.length != icySources_.length) revert ICSourceMismatch();
        if (vkConstants_ == address(0)) revert InvalidVKConstants();
        if (icLen_ == 0) revert InvalidICLength();

        VKPointers storage vk = epochVkRegistry[maxTransfers][maxInputsPerTransfer][maxOutputsPerTransfer];
        vk.icxSources = icxSources_;
        vk.icySources = icySources_;
        vk.vkConstants = vkConstants_;
        vk.icLen = icLen_;
    }

    /// @notice Verify an epoch proof for a specific circuit configuration
    /// @param maxTransfers Maximum number of transfers in circuit
    /// @param maxInputsPerTransfer Maximum inputs per transfer
    /// @param maxOutputsPerTransfer Maximum outputs per transfer
    /// @param proof Groth16 proof [A.x, A.y, B.x1, B.x0, B.y1, B.y0, C.x, C.y]
    /// @param publicInputs Public inputs to the circuit
    /// @return True if proof is valid
    function verifyEpoch(
        uint32 maxTransfers,
        uint32 maxInputsPerTransfer,
        uint32 maxOutputsPerTransfer,
        uint256[8] calldata proof,
        uint256[] calldata publicInputs
    ) external view returns (bool) {
        // Suppress unused variable warning - proof is read via calldataload at proofOffset
        proof;

        VKPointers storage vk = epochVkRegistry[maxTransfers][maxInputsPerTransfer][maxOutputsPerTransfer];
        if (vk.vkConstants == address(0)) revert VerifyingKeyNotFound();

        // Calldata layout: selector (4) + maxTransfers (32) + maxInputsPerTransfer (32) + maxOutputsPerTransfer (32) + proof starts at 0x64
        _verifyProof(0x64, publicInputs, vk);
        return true;
    }
}
