// SPDX-License-Identifier: Apache-2.0
/*
 * Copyright (c) 2026 Sunnyside Labs Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Originally generated by gnark (https://github.com/consensys/gnark)
 * Modified by Sunnyside Labs Inc.
 */
pragma solidity 0.8.34;

import {Groth16Verifier} from "./Groth16Verifier.sol";

/// @title Groth16DepositVerifier
/// @notice Groth16 verifier for deposit proofs with multi-batchSize support
contract Groth16DepositVerifier is Groth16Verifier {
    constructor(address initialOwner) Groth16Verifier(initialOwner) {}

    /// @notice Verify a deposit proof for a specific batch size
    /// @param batchSize The batch size of this deposit epoch
    /// @param proof Groth16 proof [A.x, A.y, B.x1, B.x0, B.y1, B.y0, C.x, C.y]
    /// @param publicInputs Public inputs to the circuit
    /// @return True if proof is valid
    function verifyDeposit(uint32 batchSize, uint256[8] calldata proof, uint256[] calldata publicInputs)
        external
        view
        returns (bool)
    {
        // Suppress unused variable warning - proof is read via calldataload at proofOffset
        proof;

        VKPointers storage vk = vkRegistry[batchSize];
        if (vk.vkConstants == address(0)) revert VerifyingKeyNotFound();

        // Calldata layout: selector (4) + batchSize (32) + proof starts at 0x24
        _verifyProof(0x24, publicInputs, vk);
        return true;
    }
}
